### PR TITLE
Support Create 0.5.1+ by Adding a `>=` prefix

### PR DESCRIPTION
**Pull request by KrLite**

### CODE REVIEW

**Comment by KrLite** [comment]
@JieningYu It is blocking **Cabricality** from running.

**Comment by JieningYu** [comment]
wdym

> @JieningYu It is blocking **Cabricality** from running.

**Comment by KrLite** [comment]
> wdym
> 
> > @JieningYu It is blocking **Cabricality** from running.

This mod is required by **Cabricality** but does not support any **Create** versions except `0.5.1` explicitly.

**Comment by TexBlock** [comment]
Merged in `0.1.5-create0.5.1-mc1.18.x`!

**Comment by TexBlock** [comment]
Merged in `0.1.5-create0.5.1-mc1.18.x`!

**Pull request merged**
